networks:
  proxy-net:
    external: true

services:
  tasks.md:
    image: baldissaramatheus/tasks.md:3.2.2
    networks:
      - proxy-net
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - tasks-data:/tasks
      - tasks-config:/config
    restart: unless-stopped
    ports:
      - 8050:8080

volumes:
  tasks-data:
  tasks-config:
