networks:
  proxy-net:
    external: true

services:
  tasks-md:
    image: baldissaramatheus/tasks.md:3.2.2
    networks:
      - proxy-net
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /media/sambashare/tasks:/tasks
      - /home/william/tasks-config:/config
    ports:
      - 8050:8080
    deploy:
      restart_policy:
        condition: any
