volumes:
  etc_wireguard:
    name: etc_wireguard

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:14
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    secrets:
      - wg_host
      - wg_password_hash
    environment:
      LANG: en
      WG_DEFAULT_DNS: 10.8.1.3
      WG_ALLOWED_IPS: 192.168.0.0/24,10.8.0.0/16
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        export WG_HOST=$$(cat /run/secrets/wg_host)
        export PASSWORD_HASH=$$(cat /run/secrets/wg_password_hash)
        cd /app && exec /usr/bin/dumb-init node server.js
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2
    deploy:
      restart_policy:
        condition: any

networks:
  wg-easy:
    name: wg-easy
    ipam:
      config:
       - subnet: 10.8.1.0/24

secrets:
  wg_host:
    external: true
  wg_password_hash:
    external: true
