---
networks:
  proxy-net:
    external: true

services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d authentik -U authentik"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    networks:
      proxy-net:
      default:
    volumes:
      - database:/var/lib/postgresql/data
    secrets:
      - authentik_pg_pass
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/authentik_pg_pass
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    deploy:
      restart_policy:
        condition: any

  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    networks:
      proxy-net:
      default:
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    deploy:
      restart_policy:
        condition: any

  authentik-server:
    image: ghcr.io/goauthentik/server:2025.4.1
    command: server
    secrets:
      - authentik_secret_key
      - authentik_pg_pass
    environment:
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret_key
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/authentik_pg_pass
    networks:
      proxy-net:
      default:
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    ports:
      - "9000:9000"
      - "9443:9443"
    deploy:
      restart_policy:
        condition: any

  worker:
    image: ghcr.io/goauthentik/server:2025.4.1
    command: worker
    secrets:
      - authentik_secret_key
      - authentik_pg_pass
    environment:
      AUTHENTIK_SECRET_KEY: file:///run/secrets/authentik_secret_key
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/authentik_pg_pass
    user: root
    networks:
      proxy-net:
      default:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    deploy:
      restart_policy:
        condition: any

volumes:
  database:
    name: authentik-database
  redis:
    name: authentik-redis

secrets:
  authentik_secret_key:
    external: true
  authentik_pg_pass:
    external: true
