services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:4.7.0
    environment:
      TZ: Etc/UTC
    ports:
      - "8443:8443"
      - "8123:8123"
      - "19132:19132/udp"
      - "25500-25600:25500-25600"
    volumes:
      - ./docker/backups:/crafty/backups
      - ./docker/logs:/crafty/logs
      - ./docker/servers:/crafty/servers
      - ./docker/config:/crafty/app/config
      - ./docker/import:/crafty/import
    deploy:
      restart_policy:
        condition: any
