services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:4.7.0
    restart: always
    environment:
      TZ: Etc/UTC
    ports:
      - "8443:8443"
      - "8123:8123"
      - "19132:19132/udp"
      - "25500-25600:25500-25600"
    volumes:
      - crafty-backups:/crafty/backups
      - crafty-logs:/crafty/logs
      - crafty-servers:/crafty/servers
      - crafty-config:/crafty/app/config
      - crafty-import:/crafty/import

volumes:
  crafty-backups:
  crafty-logs:
  crafty-servers:
  crafty-config:
  crafty-import:
