networks:
  proxy-net:
    external: true

services:
  copyparty:
    image: copyparty/ac:1.20.0
    user: "1000:1000"
    networks:
      proxy-net:
    ports:
      - 3923:3923
    configs:
      - source: copyparty_conf
        target: /cfg/copyparty.conf
    volumes:
      - /media/sambashare/:/w:z
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.NOPE
      PYTHONUNBUFFERED: 1
    stop_grace_period: 15s
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s
    deploy:
      restart_policy:
        condition: any

configs:
  copyparty_conf:
    external: true
